server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
  port: 8081

spring:
  application:
    name: payment
  datasource:
    name: payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: root
  profiles:
    active: dev

mybatis:
  typeAliasesPackage: com.entity
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml